config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users

  get 'board/:id' => 'boards#destroy', as: :delete

  get 'board/:id/images/new' => 'images#new', as: :addimage

  post 'board/:id/images' => 'images#create', as: :postimage

  patch 'users/:id' => 'users#update', as: :updateusers

  resources :favorite_boards, only: [:create, :destroy, :show]

  resources :followed_users, only: [:create, :destroy, :show]

  resources :boards

  resources :images, only: [:new, :create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  get '/logout' => 'sessions#destroy'

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :images, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :user
  belongs_to :followed, polymorphic: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :board
  has_one :user, through: :boards

  has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :favorites
  has_many :favorite_boards, through: :favorites, source: :favorited, source_type: 'Board'

  has_many :followers
  has_many :followed_users, through: :followers, source: :followed, source_type: 'User'

  has_many :boards, dependent: :destroy
  has_many :images, through: :boards

  has_attached_file :avatar, styles: { thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  # Verify that an email exists and that it does not already exist in the db
  validates :email, presence: true, uniqueness: true
  validates :password_confirmation, presence: true, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if current_user.nil?
      redirect_to login_path, alert: 'You must be logged in!'
    end
  end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # before_action :set_board, only: [:show, :edit, :update, :destroy]
  # before_action :authorize, except: [:index, :show]

  # GET /boards
  def index
    @boards = Board.all
  end

  # GET /boards/1
  def show
    @board = Board.find(params[:id])
    @favorite = Favorite.new
    @user = @board.user_id
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  def create
    # @board = Board.new(board_params)
    # @board.user_id = session[:user_id]
    @user = User.find(session[:user_id])
    @board = @user.boards.new(board_params)
    if @board.save
      redirect_to board_path @board.id
    else
      render "new"
    end
  end

  # PATCH/PUT /boards/1
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # def set_board
    #   @board = Board.find(params[:id])
    # end
    def board_params
      params.require(:board).permit(:title, :description, :user_id)
    end

end

app/controllers/favorite_boards_controller.rb
class FavoriteBoardsController < ApplicationController
  before_action :set_board

  def create
    if Favorite.create(favorited: @board, user: current_user)
      redirect_to @board, notice: 'Added to favorites!'
    else
      redirect_to @board, alert: 'Something went wrong...'
    end
  end

  def destroy
    Favorite.where(favorited_id: @board.id, user_id: current_user.id).first.destroy
    redirect_to @board, notice: 'Removed from favorites!'
  end

  def show
    @favorite = Favorite.find(params[:board_id])
    @board = Board.find(params[:id])
    @favboard = @board.id(@favorite)
  end

  private

  def set_board
    @board = Board.find(params[:board_id] || params[:id])
  end
end

app/controllers/followed_users_controller.rb
class FollowedUsersController < ApplicationController
  before_action :set_follower

  def create
    if Follower.create(followed: @user, user: current_user)
      redirect_to @user, notice: 'User was followed!'
    else
      redirect_to @user, alert: 'Something went wrong...*sad panda*'
    end
  end

  def destroy
    Follower.where(followed_id: @user.id, user_id: current_user.id).first.destroy
    redirect_to @user, notice: 'User was unfollowed'
  end

  private

  def set_follower
    @user = User.find(params[:user_id] || params[:id])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @image = Image.new
  end

  def create
    @board = Board.find(params[:id])
    @image = @board.images.new(image_params)
    if @image.save
      redirect_to board_path @board.id
    else
      render "new"
    end
  end

  def show
    @image = Image.find(params[:id])
  end
private
    # Implement Strong Params
    def image_params
      params.require(:image).permit(:url, :image, :board_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid login credentials - try again!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You did it!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  private
    # Implement Strong Params
    def user_params
      params.require(:user).permit(:username, :name, :email, :password, :password_confirmation, :avatar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/favorite_boards_helper.rb
module FavoriteBoardsHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', current_user %>

app/views/boards/show.html.erb
<div class="thingholder">
  <div class="aboutsenction">
    <h3><%= @board.title %></h3>
    <h5><%= @board.description %></h5>
  </div>
  <div class="gallery">
    <% link_to image_path%>
      <figure>
        <% @board.images.each do |image| %>
          <%= image_tag(image.image, size: "250x250", alt: "mood board image") %>
        <% end %>
      </figure>
  </div>

  <br>
  <p>
    <% if current_user && current_user.id == @user.to_i %>
      <button type=""><%= link_to 'Upload Images', addimage_path %></button>
      <button type=""><%= link_to 'Edit', edit_board_path %></button>
      <button type=""><%= link_to 'Delete', delete_path %></button>
    <% else %>
      <%- unless current_user.favorite_boards.exists?(id: @board.id) -%>
        <button><%= link_to 'Add to favorites', favorite_boards_path(board_id: @board), method: :post %></button>
      <%- else -%>
        <button><%= link_to 'Remove from favorites', favorite_board_path(@board), method: :delete %></button>
      <%- end -%>
    <% end %>
  </p>
</div>

app/views/images/new.html.erb
<h1>Upload Image</h1>

<%= form_for(@image, html: {multipart: true}, url: postimage_path) do |f| %>

  <div class="field">
    <%= f.label "Upload Image" %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<button><%= link_to 'Back', board_path %></button>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoodBoarderApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <div class="navbar-brand"><%= link_to 'MOOD BOARDER', root_path %></div>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <ul class="nav navbar-nav">
            <li><%= link_to "Users", users_path %>
          <% if current_user %>
            <li><%= link_to current_user.username, current_user %></li>
            <li><%= link_to 'Log Out', session_path('dummy'), method: :delete %></li>
          <% else %>
            <li><%= link_to 'Log In', login_path %></li>
            <li><%= link_to 'Sign Up', new_user_path %></li>
          <% end %>
        </ul>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, url: updateusers_path, html: { multipart: true } do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
    <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <% if request.original_url["edit"] %>
    <div class="field">
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>
  <% end %>
  <div class="actions"><%= f.submit %></div>
  <% end %>

app/views/users/create.html.erb
<h1>users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit Your Information</h1>

<%= form_for @user, url: updateusers_path, html: { multipart: true } do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
    <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <% if request.original_url["edit"] %>
    <div class="field">
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>
  <% end %>
  <div class="actions"><%= f.submit %></div>
  <% end %>

<button><%= link_to 'Back', user_path(@user) %></button>

app/views/users/index.html.erb
<h1 class="indexheader">Explore Users</h1>
<div class="container usergrid">
  <div class="col-sm-6 col-md-8">
    <div class="userlist">
      <% @users.each do |user| %>
        <% if user.avatar_file_name == nil %>
          <%= image_tag("missing.png", size: "100x100", :alt => "it's missing") %>
        <% else %>
          <%= image_tag user.avatar.url(:thumb) %>
        <% end %>
        <button class="btn btn-info">
          <%= link_to user.username, user_path(id: user.id) %>
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user, url: users_path, html: { multipart: true } do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<form>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
    <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <% if request.original_url["edit"] %>
    <div class="field">
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>
  <% end %>
  <div class="actions"><%= f.submit %></div>
  <% end %>
</form>

app/views/users/show.html.erb
<!-- Profile Page -->

<div class="container">
  <div class="boardcontainer col-xs-12 col-sm-6">
    <div class="face"><% if @user.avatar_file_name == nil %>
            <%= image_tag("missing.png", :alt => "it's missing") %>
          <% else %>
            <%= image_tag @user.avatar.url(:thumb) %>
          <% end %>
    </div>
    <div class="text">
      <h1 class="headline"><%= @user.username %></h1>
      <p class="buttons"><% if current_user && current_user.id == @user.id %>
        <button type="button" id="editprofile" class="btn"><span class=""><%= link_to 'Edit', edit_user_path %></span></button>
        <button type="button" id="editprofile" class="btn"><span class=""><%= link_to 'Delete', delete_path %></span></button>
      <% else %>
        <%- unless current_user.followed_users.exists?(id: @user.id) -%>
          <button type="button" class="btn"><%= link_to 'Follow', followed_users_path(user_id: @user), method: :post %> </button>
        <%- else -%>
          <button type="button" class="btn"><%= link_to 'Unfollow', followed_user_path(@user), method: :delete %> </button>
        <%- end -%>
      <% end %></p>
    </div>
  </div>
</div>
<div class="container">
  <br><br>
  <div class="boardcontainer col-xs-12 col-sm-6">
    <div class="boardholder">
        <h3>Boards</h3>
        <% @user.boards.each do |board| %>
        <ul>
          <li><%= link_to(board.title, board_path(board.id)) %></li>
        </ul>
        <% end %>
      <% if current_user && current_user.id == @user.id %>
        <button type="button" id="boards" class="btn" ><span class="glyphicon glyphicon-plus" aria-hidden="true"></span><%= link_to 'New Board', new_board_path %></button>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container-fluid">
  <div class="jumbotron ">
    <div class="page-header">
      <h1 class="logo">Mood Boarder</h1>
    <p>Make mood boards! Upload images to create your own or browse other users' boards to get inspired!</p>
    </div>
    <p><button class="btn btn-info"><%= link_to 'Sign Up!', new_user_path %></button></p>
  </div>
  <div class="row">
    <div class="col-sm-6 col-md-3 col-lg-3">
      <div class="thumbnail">
        <%= image_tag "branding.jpg", size: "200x200>" %>
        <div class="caption">
          <h3>Branding</h3>
          <p>Collect on-brand imagery for inspiration and brand development!</p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= image_tag "webdesign.jpg" %>
        <div class="caption">
          <h3>Web Design</h3>
          <p>Gather ideas and get inspired by designes you like!</p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= image_tag "fashion.jpg" %>
        <div class="caption">
          <h3>Fashion</h3>
          <p>Build a cohesive wardrobe that conveys your personal image!</p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= image_tag "intdesign.jpg" %>
        <div class="caption">
          <h3>Interior Design</h3>
          <p>Develop a unique look for a home or business!</p>
        </div>
      </div>
    </div>
  </div>
</div>